[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "qmlh5"
version = "1.2.0"
description = "QuakeML to HDF5 read/write utility for ObsPy earthquake catalog objects"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
dependencies = ['obspy','h5py','numpy']
